2025-04-27T16:31:16.270033Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T16:31:16.271266Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T16:31:16.270681Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T16:31:16.270458Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T16:31:16.270958Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"2025-04-27T16:42:16.554196Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T16:42:16.554296Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T16:42:16.554002Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T16:42:16.554475Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T16:42:16.554385Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"2025-04-27T16:42:39.512993Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T16:42:39.513576Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T16:42:39.513191Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T16:42:39.512646Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T16:42:39.513353Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"2025-04-27T17:17:03.690969Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T17:17:03.689598Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T17:17:03.690152Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T17:17:03.690366Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T17:17:03.690834Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:13)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"2025-04-27T17:23:27.992601Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T17:23:27.993176Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T17:23:27.992972Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T17:23:27.992839Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T17:23:27.993082Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:14)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"2025-04-27T17:35:44.232692Z,WARN,main,SampleApp,This is a warning message.,,2025-04-27T17:35:44.233034Z,INFO,main,SampleApp,This uses a lambda for potentially expensive message creation.,,2025-04-27T17:35:44.232391Z,INFO,main,SampleApp,This is an informational message.,,2025-04-27T17:35:44.232814Z,ERROR,main,SampleApp,This is an error message.,,2025-04-27T17:35:44.232943Z,ERROR,main,SampleApp,An error occurred during processing.,,"java.lang.RuntimeException: Something went wrong!
	at io.github.khoaluong.logging.SampleAppKt$main$1.invokeSuspend(SampleApp.kt:48)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt:14)
	at io.github.khoaluong.logging.SampleAppKt.main(SampleApp.kt)
"